## 作業目標：運用scikit-learn API 實現K-fold分割資料

---

### 讀入資料

In [1]:
import pandas as pd
dataset = pd.read_csv(r'Social_Network_Ads.csv')

In [2]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

### 取出訓練特徵與標註

In [3]:
dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values

array([[15624510, 'Male', 19.0, 19000.0],
       [15810944, 'Male', 35.0, 20000.0],
       [15668575, 'Female', 26.0, 43000.0],
       ...,
       [15654296, 'Female', 50.0, 20000.0],
       [15755018, 'Male', 36.0, 33000.0],
       [15594041, 'Female', 49.0, 36000.0]], dtype=object)

In [4]:
X = dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values
Y = dataset['Purchased'].values

---

In [5]:
import numpy as np
from sklearn.model_selection import KFold

### 將訓練資料按照順序切割成10等分

In [8]:
# 預設為5
kf = KFold()
kf.get_n_splits(X)

print(kf)


KFold(n_splits=5, random_state=None, shuffle=False)


In [6]:

kf = KFold(10)
kf.get_n_splits(X)

print(kf)


KFold(n_splits=10, random_state=None, shuffle=False)


### 將訓練資料隨機切割成10等分

In [12]:
kf = KFold(10, shuffle=True)
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


In [28]:
kf = KFold("自行填入")
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


---

### 取出 切割資料對應位置

In [10]:
train_split = kf.split(X)
next(train_split)

(array([  0,   1,   2,   4,   5,   6,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  34,  35,  36,  37,  38,  40,  41,  42,
         43,  44,  45,  46,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  61,  62,  63,  64,  65,  66,  67,  68,  69,  71,
         72,  73,  76,  77,  78,  79,  80,  81,  82,  83,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 139, 141, 144,
        145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
        186, 187, 188, 189, 190, 191, 192, 193, 194

### Or

In [13]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  85  86  87  88  89  91  92  94
  95  96  97  98 100 101 102 103 105 107 108 109 110 111 112 113 114 115
 116 117 119 120 122 123 124 125 127 128 129 131 132 134 135 136 137 138
 139 141 142 143 145 146 147 148 149 150 151 152 153 154 155 156 157 158
 159 160 161 162 163 165 167 168 169 170 171 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 189 190 191 192 193 194 195 196 197 198 199
 200 201 203 204 205 206 207 208 209 210 211 212 213 214 215 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 234 235 237 238 239
 240 241 242 243 244 246 247 248 249 250 251 252 253 254 255 256 258 259
 260 261 262 263 264 265 267 268 269 270 272

### 取出切割資料：trainset / testset 特徵(x_train/x_test)/標註(y_train/y_test)

In [16]:
train_index, test_index = kf.split(X)

ValueError: too many values to unpack (expected 2)

In [19]:
X

array([15624510, 'Male', 19.0, 19000.0], dtype=object)

In [21]:
for train_index, test_index in kf.split(X):
    print("X_TRAIN:", X[train_index], "X_TEST:", X[test_index])
    print("Y_TRAIN:", Y[train_index], "Y_TEST:", Y[test_index])

X_TRAIN: [[15624510 'Male' 19.0 19000.0]
 [15810944 'Male' 35.0 20000.0]
 [15668575 'Female' 26.0 43000.0]
 ...
 [15654296 'Female' 50.0 20000.0]
 [15755018 'Male' 36.0 33000.0]
 [15594041 'Female' 49.0 36000.0]] X_TEST: [[15728773 'Male' 27.0 58000.0]
 [15598044 'Female' 27.0 84000.0]
 [15727311 'Female' 35.0 65000.0]
 [15746139 'Male' 20.0 86000.0]
 [15621083 'Female' 48.0 29000.0]
 [15792818 'Male' 49.0 28000.0]
 [15724858 'Male' 27.0 90000.0]
 [15583681 'Male' 32.0 120000.0]
 [15592877 'Male' 32.0 18000.0]
 [15636428 'Female' 30.0 116000.0]
 [15642725 'Male' 40.0 59000.0]
 [15638963 'Female' 21.0 68000.0]
 [15750839 'Female' 27.0 96000.0]
 [15679651 'Female' 26.0 15000.0]
 [15576219 'Male' 41.0 45000.0]
 [15599533 'Female' 37.0 33000.0]
 [15614827 'Female' 35.0 71000.0]
 [15594577 'Male' 25.0 22000.0]
 [15680243 'Female' 20.0 36000.0]
 [15628523 'Male' 35.0 39000.0]
 [15735549 'Female' 39.0 134000.0]
 [15694879 'Male' 37.0 144000.0]
 [15593715 'Male' 60.0 102000.0]
 [15614187 'Male